### ISSUE TITLE
Add different emojis for each coin in the tweet

### ISSUE THREAD

**Issue by theyashwanthsai** [theyashwanthsai/TwitterBotCryptoPrice#25]
Add these emojis to make the tweets look better:
💰 💸  🤑  💵  🪙  🏦  📊  📈 
or any other suitable emoji
Keep in mind the limit for each tweet...

**Comment by KunalMaverick** [comment]
can i get assigned to this

**Comment by ad1tya24** [comment]
I would like to work on this

**Comment by samarth777** [comment]
can you assign this to me

**Comment by its-abhishek** [comment]
I would work on to this issue

**Comment by theyashwanthsai** [comment]
> I would like to work on this

First come first serve, please work on the issue :)
