### ISSUE TITLE
Add few NFT coins (keep in mind that the max tweet length is 280)

### ISSUE THREAD

**Issue by theyashwanthsai** [theyashwanthsai/TwitterBotCryptoPrice#26]
[Refer](https://www.coingecko.com) to this website and use the [coin gecko api](https://www.coingecko.com/en/api/documentation)
Add the coins in the net category.
Add 3-4 coins and all in a new line and each having an emoji.

![Screenshot 2022-10-22 at 3 17 16 AM](https://user-images.githubusercontent.com/68785131/197293676-a55c6792-383f-412e-970b-16c717f801f4.png)

Make it something similar to this.

**Comment by ramselvaraj** [comment]
hey can i get assigned to this?

**Comment by theyashwanthsai** [comment]
You have been assigned @ramselvaraj 
Please work on the issue 😃

**Comment by ramselvaraj** [comment]
> You have been assigned @ramselvaraj Please work on the issue 😃
yes doing lol

**Comment by ramselvaraj** [comment]
does the tweet have to include the original coin prices as well?

**Comment by its-abhishek** [comment]
I would work on this issue

**Comment by theyashwanthsai** [comment]
> does the tweet have to include the original coin prices as well?

original? use inr prices.
try adding coins like ApeCoin, Chilliz, Axie Infinity, etc

**Comment by Vaarun-Kamath** [comment]
can i work on this?
