### ISSUE TITLE
All the contents are in a single line, make them organised, add emojis

### ISSUE THREAD

**Issue by theyashwanthsai** [theyashwanthsai/TwitterBotCryptoPrice#4]
Right now all the prices are unorganised, and not much readable.

![Screenshot 2022-10-19 at 10 37 29 PM](https://user-images.githubusercontent.com/68785131/196758147-40988fdf-561b-48bc-b75b-05dfaa648df7.png)

Refer to this tweet.

**Comment by Keshav1105** [comment]
Is it done or can i put my pull request

**Comment by theyashwanthsai** [comment]
> Is it done or can i put my pull request

Till 8:30 its open for all
