### ISSUE TITLE
Add USD prices for BTC, ETH, MATIC

### ISSUE THREAD

**Issue by theyashwanthsai** [theyashwanthsai/TwitterBotCryptoPrice#8]
Tweet the us prices right after the Indian prices.
Each BTC, ETH,MATIC must be in a separate tweet.

Use the [coingecko api ](https://www.coingecko.com/en/api/documentation)

**Comment by Vaarun-Kamath** [comment]
Hey can i get this :)

**Comment by TejasB02** [comment]
@theyashwanthsai Can I work on this

**Comment by KunalMaverick** [comment]
Can i get to work on this

**Comment by theyashwanthsai** [comment]
@KunalMaverick @TejasB02 @Vaarun-Kamath 
Anyone can work on the issues for the first hour :)

**Comment by ramselvaraj** [comment]
Does the presentation of the tweet matter? Like using the Rupee and Dollar symbols, Formatting the tweet etc.

**Comment by KunalMaverick** [comment]
assign me again

**Comment by ramselvaraj** [comment]
hey can i get assigned to this?
