### ISSUE TITLE
MANA and SAND 

### ISSUE THREAD

**Issue by theyashwanthsai** [theyashwanthsai/TwitterBotCryptoPrice#9]
Need a separate tweet. Use the coingecko API. (/simple/price)
(https://www.coingecko.com/en/api/documentation)

**Comment by Keshav1105** [comment]
Can i get the issue

**Comment by Harshit-crypto** [comment]
SRN: PES2UG20CS136 
NAME : HARSHIT JAIN
can i get the issue
